<a href="https://colab.research.google.com/github/sancarhacer/DataSciencewithPython/blob/main/8_DataFramesApply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("8-apply_function_data.csv")
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [ ]:
df[1:20]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [ ]:
# Example 1: Apply a function to classify employees based on salary
def salary_category(salary):
    if salary < 50000:
        return "Low"
    elif 50000 <= salary < 80000:
        return "Medium"
    else:
        return "High"
df["Salary_Category"] = df["Salary"].apply(salary_category)
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [ ]:
# Example 2: Apply a function to calculate adjusted performance score
def adjust_performance(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] + 1
    return row["Performance_Score"]
df["Adjusted_Performance"] = df.apply(adjust_performance, axis=1)
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Performance
0,1,Emp_1,Marketing,82251,6,5,High,5
1,2,Emp_2,Sales,52662,24,3,Medium,4
2,3,Emp_3,Finance,38392,5,3,Low,3
3,4,Emp_4,Sales,60535,20,3,Medium,4
4,5,Emp_5,Sales,108603,2,2,High,2
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5
96,97,Emp_97,Sales,100467,22,2,High,3
97,98,Emp_98,IT,82662,23,3,High,4
98,99,Emp_99,IT,42688,22,1,Low,2
99,100,Emp_100,HR,55342,14,3,Medium,4

In [ ]:
# Example 3: Apply a lambda function to format employee names
df["Name"] = df["Name"].apply(lambda x: x.replace("_", " "))
df.head()

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Performance
0,1,Emp 1,Marketing,82251,6,5,High,5
1,2,Emp 2,Sales,52662,24,3,Medium,4
2,3,Emp 3,Finance,38392,5,3,Low,3
3,4,Emp 4,Sales,60535,20,3,Medium,4
4,5,Emp 5,Sales,108603,2,2,High,2